GET http://localhost:8080/getClue
Accept: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJpdGZlc3QtMi4wIiwiZXhwIjoxNjc1MjI4NDgwLCJpZCI6Nywicm9sZSI6InVzZXIifQ.ObehVMi-eFY-mU5gc7RbmO4pjPnuWGHiCDkeL2KrsKA
