POST http://localhost:8080/login
Content-Type: application/json

{
  "username" : "itfest-admin",
  "password" : "itfest-admin"
}

> {% client.global.set("auth_token", response.body.data); %}

###

POST http://localhost:8080/addMerchandise
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Tumblr Arkavidia",
  "stock": 10,
  "point": 2000
}