POST http://localhost:8080/login
Content-Type: application/json

{
  "username" : "itfest",
  "password" : "itfest"
}

> {% client.global.set("auth_token", response.body.data); %}

###

POST http://localhost:8080/grantPoint
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "usercode" : "307691",
  "point": 200
}