POST http://localhost:8080/register
Content-Type: application/json

{
  "name" : "itfest",
  "username" : "itfest",
  "password" : "itfest"
}

###

POST http://localhost:8080/register
Content-Type: application/json

{
  "name" : "itfest user",
  "username" : "itfest-user",
  "password" : "itfest-user"
}

###

POST http://localhost:8080/register
Content-Type: application/json

{
  "name" : "itfest admin",
  "username" : "itfest-admin",
  "password" : "itfest-admin"
}
